def cmd_help():
    print(
        "Help:\n"
        "To add a new profile, type string with following template.\n"
        "{ID: 7},{Name: < 70},{Year: 4}-{Month: < 3}-{Date: < 3},"
        "{Addr: < 70},{Comm: Any}\n"
        "Numbers are the characters you can insert.\n"
        "\n"
        "To run functions, type command and parameter with following template.\n"
        "%%{Command} {Parameter}\n"
        "\n"
        "---List of Commands---\n"
        "H (Help)  : Show command list for help\n"
        "     Param:\n"
        "Q (Quit)  : Close and quit the program\n"
        "     Param:\n"
        "C (Count) : Count and show the number of profiles in memory\n"
        "     Param:\n"
        "P (Print) : Print profiles in memory\n"
        "     Param: 0 - Show all\n"
        "     {Positive number} - Show profiles from the first one to the number's\n"
        "     {Negative number} - Show profiles from the number's one to the last\n"
        "R (Read)  : Read and insert profiles into memory from CSV file\n"
        "     Param: {filename}.csv\n"
        "W (Write) : Write profiles in memory into CSV file\n"
        "     Param: {filename}.csv\n"
        "F (Find)  : Find profiles matching a string\n"
        "     Param: {string}\n"
        "S (Sort)  : Sort profiles in memory\n"
        "     Param: 1 - Sort by ID\n"
        "D (Delete): Delete a profile in memory\n"
        "     Param: {Profile No.}\n"
    )
    return
